apiVersion: network.aws.crossplane.io/v1alpha3
kind: RouteTable
metadata:
  labels:
    provider: aws
  name: argo-routetable
spec:
  associations:
  - subnetIdRef:
      name: argo-subnet1
  - subnetIdRef:
      name: argo-subnet2
  - subnetIdRef:
      name: argo-subnet3
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  routes:
  - destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: argo-internetgateway
  vpcIdRef:
    name: argo-vpc