apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  labels:
    provider: aws
  name: argo-subnet1
spec:
  name: argo-subnet1
  availabilityZone: ap-southeast-2a
  cidrBlock: 30.0.64.0/18
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  vpcIdRef:
    name: argo-vpc