apiVersion: network.aws.crossplane.io/v1alpha3
kind: VPC
metadata:
  labels:
    provider: aws
  name: argo-vpc
spec:
  cidrBlock: 30.0.0.0/16
  enableDnsHostNames: true
  enableDnsSupport: true
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
