apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks
spec:
  destination:
    name: in-cluster
    namespace: default
    server: ''
  source:
    path: crossplane
    repoURL: 'https://github.com/rajeshsanthalingam/Docker.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: null